server:
  port: 9793
  servlet:
    context-path: /shardingsphere-jdbc-server
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    password: dsJ34jF

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-src.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 400MB
      max-request-size: 400MB