# Diff Configuration for checking master-slave consistency

######################### Global config #########################
check-thread-count = 8
export-fix-sql = true
check-data-only = false
check-struct-only = false
skip-non-existing-table = true

######################### Datasource config #########################
[data-sources]
[data-sources.master]
host = "127.0.0.1"
port = 3308
user = "root"
password = "root"

[data-sources.slave]
host = "127.0.0.1"
port = 3313
user = "root"
password = "root"

######################### Task config #########################
[task]
output-dir = "./output"
source-instances = ["master"]
target-instance = "slave"
target-check-tables = [
    "sharding_db.t_city",
    "sharding_db.t_ent_order",
    "sharding_db.t_ent_order_detail",
    "sharding_db.t_ent_order_item",
]
# # 添加对特殊表配置的引用
# target-configs = ["ignore_time_config"]
#
# ######################### Table config #########################
# # 配置忽略时间字段的特殊配置
# [table-configs.ignore_time_config]
# # 应用到所有需要忽略时间字段的表
# target-tables = ["sharding_db.t_city", "sharding_db.t_ent_order", "sharding_db.t_ent_order_detail", "sharding_db.t_ent_order_item"]
# # 忽略 create_time 和 update_time 字段的差异
# ignore-columns = ["create_time", "update_time"]