# Diff Configuration for checking master-slave consistency

######################### Global config #########################
check-thread-count = 8
export-fix-sql = false
check-data-only = false
check-struct-only = false
skip-non-existing-table = true

######################### Datasource config #########################
[data-sources]
[data-sources.master]  # Master database (原 mysql1)
host = "127.0.0.1"
port = 3308
user = "root"
password = "root"
# route-rules = ["rule1"]
# snapshot = "auto"

[data-sources.slave]   # Slave database (原 tidb0)
host = "127.0.0.1"
port = 3313
user = "root"
password = "root"
# security.ca-path = ".../ca.crt"
# security.cert-path = ".../cert.crt"
# security.key-path = ".../key.crt"
# snapshot = "auto"

########################### Routes ###########################
# 不需要分表路由规则，全部注释掉
# [routes]
# [routes.rule1]
# schema-pattern = "sharding_db"
# table-pattern = "t_*"
# target-schema = "sharding_db"
# target-table = "t_*"

######################### Task config #########################
[task]
output-dir = "./output"
source-instances = ["master"]
target-instance = "slave"

# 精确指定需要检查的表（原 target-check-tables = ["sharding_db.t_*"]）
target-check-tables = [
    "sharding_db.t_city",
    "sharding_db.t_ent_order",
    "sharding_db.t_ent_order_detail",
    "sharding_db.t_ent_order_item"
]
# target-configs = ["config1"]

######################### Table config #########################
# 不需要特殊表配置，全部注释掉
# [table-configs.config1]
# target-tables = ["schema*.test*", "test2.t2"]
# range = "age > 10 AND age < 20"
# index-fields = ["col1","col2"]
# ignore-columns = ["",""]
# chunk-size = 0
# collation = ""