version: "3.8"

services:
  mysql-0:
    image: mysql:8.0
    container_name: mysql-0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_0
    ports:
      - "3309:3306"
    volumes:
      - dst-mysql-0-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dst-sharding-network
      - shared_network

  mysql-1:
    image: mysql:8.0
    container_name: mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_1
    ports:
      - "3310:3306"
    volumes:
      - dst-mysql-1-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dst-sharding-network
      - shared_network

  mysql-2:
    image: mysql:8.0
    container_name: mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_2
    ports:
      - "3311:3306"
    volumes:
      - dst-mysql-2-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dst-sharding-network
      - shared_network

  mysql-3:
    image: mysql:8.0
    container_name: mysql-3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_3
    ports:
      - "3312:3306"
    volumes:
      - dst-mysql-3-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dst-sharding-network
      - shared_network

  sharding-proxy:
    image: apache/shardingsphere-proxy:5.3.2
    container_name: dst-sharding-proxy
    depends_on:
      - mysql-0
      - mysql-1
      - mysql-2
      - mysql-3
    ports:
      - "3313:3308"
    volumes:
      - ./dst-config:/opt/shardingsphere-proxy/conf
      - ./ext-lib:/opt/shardingsphere-proxy/ext-lib
    networks:
      - dst-sharding-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass dsJ34jF
    volumes:
      - dst-redis-data:/data
    networks:
      - dst-sharding-network

volumes:
  dst-mysql-0-data:
  dst-mysql-1-data:
  dst-mysql-2-data:
  dst-mysql-3-data:
  dst-redis-data:

networks:
  dst-sharding-network:
    driver: bridge
  shared_network:
    external: true
