version: "3.8"

services:
  src-mysql-0:
    image: mysql:8.0
    container_name: src-mysql-0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_0
    ports:
      - "3306:3306"
    volumes:
      - mysql-0-data:/var/lib/mysql
      - ./src-config/mysql-0-conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --binlog-format=ROW --server-id=1
    networks:
      - src-sharding-network
      - shared_network

  src-mysql-1:
    image: mysql:8.0
    container_name: src-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ds_1
    ports:
      - "3307:3306"
    volumes:
      - mysql-1-data:/var/lib/mysql
      - ./src-config/mysql-1-conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --log-bin=mysql-bin --binlog-format=ROW --server-id=2
    networks:
      - src-sharding-network
      - shared_network

  src-sharding-proxy:
    image: apache/shardingsphere-proxy:5.3.2
    container_name: src-sharding-proxy
    depends_on:
      - src-mysql-0
      - src-mysql-1
    ports:
      - "3308:3308"
    volumes:
      - ./src-config:/opt/shardingsphere-proxy/conf
      - ./ext-lib:/opt/shardingsphere-proxy/ext-lib
    networks:
      - src-sharding-network

  src-redis:
    image: redis:latest
    container_name: src-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass dsJ34jF
    volumes:
      - redis-data:/data
    networks:
      - src-sharding-network

volumes:
  mysql-0-data:
  mysql-1-data:
  redis-data:

networks:
  src-sharding-network:
    driver: bridge
  shared_network:
    external: true
